image: java:8

stages:
  - build
  - release
  - publish
  
maven-build-snapshot:
    image: gitlab.cambiocds.com:4567/tools/docker-builder
    stage: build
    script:
        - mvn clean package
    artifacts:
        paths:
            - cds/gdl-editor/target/*.zip
    except:
        - /^release-.*$/
        - tags

maven-build-tag:
    image: gitlab.cambiocds.com:4567/tools/docker-builder
    stage: build
    script:
        - mvn clean deploy
    artifacts:
        paths:
            - cds/gdl-editor/target/*.zip
    only:
        - tags

release:
    image: gitlab.cambiocds.com:4567/tools/docker-builder
    stage: release
    when: manual
    script:
        - git remote set-url origin $(echo $CI_BUILD_REPO | sed -e 's/[^@]\+@\([^\/]\+\)\//git@\1\:/')
        - git checkout -b release-$CURRENT_VERSION
        - git push -u origin release-$CURRENT_VERSION
        - mvn versions:set -DnewVersion=$CURRENT_VERSION
        - git commit -a -m "Changing to version "$CURRENT_VERSION
        - git tag $CURRENT_VERSION
        - git push origin $CURRENT_VERSION --tags
        - git push origin --delete release-$CURRENT_VERSION
    only:
        - master

publish-to-gdrive:
    image: icorbal/docker-ant-gdrive
    stage: publish
    script:
        - gdrive --refresh-token $GDRIVE_TOKEN upload cds/gdl-editor/target/gdl-editor-$CI_BUILD_REF_NAME-bundle.zip -p $GDRIVE_FOLDER
    dependencies:
        - maven-build-tag
    only:
        - tags
